config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources:articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 255}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action."
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    # @article = Article.find_by(id: params[:id])
  end
  
  def new
    @article = Article.new
  end

  def edit
    # @article = Article.find_by(id: params[:id])
  end

  def create
    # debugger
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    # @article.save
    # redirect_to articles_path(@article)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to articles_path(@article)
    else
      render 'new'
    end
  end

  def update
    # @article = Article.find_by(id: params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully created."
      redirect_to articles_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    # @article = Article.find_by(id: params[:id])
    @article.destroy
    flash[:notice] = "Article was successfully deleted."
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find_by(id: params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete your own articles."
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out."
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    # debugger
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog, #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
    
  def edit
      
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully."
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only edit your own account."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 150 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
end

app/views/articles/_article.html.erb
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Created by</th>
            <th>Created at</th>
            <th>Last updated</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% obj.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.user.username if article.user %></td>
            <td><%= time_ago_in_words(article.created_at) %></td>
            <td><%= time_ago_in_words(article.created_at) %></td>
            <td><%= link_to  "Show", article_path(article) %></td>
            <% if logged_in? && current_user == article.user %>
            <td><%= link_to  "Edit", edit_article_path(article) %></td>
            <td><%= link_to  "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
            <% end %> 
        </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevent the article from being created.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

<!--  form_for(@article, :html => {class: "form-horizontal", role: "form"} do |f| -->
<%= form_for(@article, :html => {role: "form"}) do |f| %>
<div class="form-group row mt-4">
  <div class="col-sm-2 col-form-label">
    <%= f.label :title, "Title of article", class: "float-right font-weight-bold" %>
  </div>
  <div class="col-sm">
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
</div>
<div class="form-group row mt-4">
  <div class="col-sm-2 col-form-label">
    <%= f.label :description, "Article description", class: "float-right font-weight-bold"  %>
  </div>
  <div class="col-sm">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description" %>
  </div>
</div>
<div class="form-group row mt-4">
  <div class="col-sm-2 offset-sm-2">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

<div class="text-center mt-4">
  <p class="lead">
    <%= link_to  "Back to articles listing", articles_path, class: "text-decoration-none" %>
  </p>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center display-4 font-weight-normal">Edit article</h1>

<%= render  "form" %>

<!-- <% if @article.errors.any? %>
<h2>The following errors prevent the article from being created.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
<p>
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description, "Description" %><br />
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to  "Back to articles listing", articles_path %> -->

app/views/articles/index.html.erb
<h1>Listing all articles.</h1>
<p>
    <%= link_to  "Create new article", new_article_path %>
</p>

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-center">
            <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
        </div>
    </div>
</div>

<%= render  "article", obj: @articles %>

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-center">
            <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center display-4 font-weight-normal">Create an article</h1>

<%= render  "form" %>

<!-- <% if @article.errors.any? %>
<h2>The following errors prevent the article from being created.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
<p>
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description, "Description" %><br />
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to  "Back to articles listing", articles_path %> -->

app/views/articles/show.html.erb
<h1>Showing selected article:</h1>

<p>
    Title: <%= @article.title %>
</p>

<% if @article.user %>
<div class="row mb-5">
    <div class="col-6 mx-auto text-center">
        <div class="card px-3 pt-4">
            <ul class="list-unstyled">
                <li>
                    <%= link_to  gravatar_for(@article.user), user_path(@article.user) %>
                </li>
                <li>
                    <%= link_to  @article.user.username, user_path(@article.user) %>
                </li>
                <li>
                    <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
                </li>
            </ul>
        </div>
    </div>
</div>
<% end %>

<p>
    Description: <%= @article.description %>
</p>
<% if logged_in? && current_user == @article.user %>
<%= link_to  "Edit this article", edit_article_path(@article) %> |
<%= link_to  "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
<% end %>
<%= link_to  "Back to articles listing", articles_path %>

app/views/layouts/_footer.html.erb
<div class="container my-5">
    <footer class="footer text-center">
        <hr>
        <small>
            Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer Course </a>by <a href="http://wwww.mashrurhossain.com">Mashrur Hossain</a>
        </small>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
<% flash.each do |name, msg| %>
<ul>
  <li><%= msg %></li>
</ul>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- <a class="navbar-brand" href="#">Alpha Blog</a> -->
    <%= link_to  "ALPHA BLOG", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to  "Articles", articles_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "About", about_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to  "New Article", new_article_path, class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to  "Edit your Profile", edit_user_path(current_user), class: "dropdown-item" %>
                    <%= link_to  "View your Profile", user_path(current_user), class: "dropdown-item" %>
                    <%= link_to  "See Users", users_path, class: "dropdown-item" %>
                </div>
            </li>
            <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
            <li class="nav-item">
                <%= link_to  "Logout", logout_path, method: :delete, class: "text-light" %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to  "Login", login_path, class: "text-light nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Sign Up", signup_path, class: "text-light nav-link" %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render  "layouts/navigation" %>
    <div class="container mt-5">
        <%= render  "layouts/messages" %>
        <!-- <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %> -->
        <%= yield %>
    </div>
    <%= render  "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
</body>

</html>

app/views/pages/about.html.erb
<h1>This is the about page.</h1>

<%= link_to image_tag('me.jpg'), "https://www.mashrurhossain.com" %>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h1 class="display-4">
        Welcome to Alpha Blog
    </h1>
    <p class="lead mt-4">
        <%= link_to  "Sign Up now", signup_path, class: "btn btn-primary" %>
    </p>
</div>




<!-- <%= image_tag 'me.jpg' %> -->

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevent your account from being created.</h2>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li>
        <%= msg %>
    </li>
    <% end %>
</ul>
<% end %>

<!--  form_for(@article, :html => {class: "form-horizontal", role: "form"} do |f| -->
<%= form_for(@user, :html => {role: "form"}) do |f| %>
<div class="form-group row mt-4">
    <div class="col-sm-2 col-form-label">
        <%= f.label :username, "Username", class: "float-right font-weight-bold" %>
    </div>
    <div class="col-sm">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
    </div>
</div>
<div class="form-group row mt-4">
    <div class="col-sm-2 col-form-label">
        <%= f.label :email, "Email", class: "float-right font-weight-bold"  %>
    </div>
    <div class="col-sm">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
</div>
<div class="form-group row mt-4">
    <div class="col-sm-2 col-form-label">
        <%= f.label :password, "Password", class: "float-right font-weight-bold"  %>
    </div>
    <div class="col-sm">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
</div>
<div class="form-group row mt-4">
    <div class="col-sm-2 offset-sm-2">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary") %>
    </div>
</div>
<% end %>

<div class="text-center mt-4">
    <p class="lead">
        <%= link_to  "Back to home", root_path, class: "text-decoration-none" %>
    </p>
</div>

app/views/users/edit.html.erb
<h1 class="display-4 font-weight-normal text-center">Edit your account</h1>

<%= render  "form" %>

app/views/users/index.html.erb
<h1 class="display-4 font-weight-normal text-center">All Alpha Blog Users</h1>

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-center">
            <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
        </div>
    </div>
</div>

<% @users.each do |user| %>
<div class="row mb-5">
    <div class="col-6 mx-auto text-center">
        <div class="card px-3 pt-4">
            <ul class="list-unstyled">
                <li>
                    <%= link_to  gravatar_for(user), user_path(user) %>
                </li>
                <li>
                    <%= link_to  user.username, user_path(user) %>
                </li>
                <li>
                    <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
                </li>
            </ul>
        </div>
    </div>
</div>
<% end %>

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-center">
            <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="display-4 font-weight-normal text-center">Sign Up for Alpha Blog</h1>

<%= render  "form" %>

app/views/users/show.html.erb
<h1 class="display-4 text-center font-weight-normal">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
    <div class="col text-center">
        <%= gravatar_for @user %>
    </div>
</div>

<h4 class="text-center"><%= @user.username %>'s Articles</h4>

<%= render  "articles/article", obj: @user.articles %>